; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "VKDrive"
#define MyAppVersion "0.1.0.7"
#define MyAppPublisher "VDrive"
#define MyAppURL "http://dnap.su/"
#define MyAppExeName "VKDrive.exe"


[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{878BB4CD-5D88-4ED5-B490-DB0144B28A56}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "ru"; MessagesFile: "Russian.isl"
;Name: "en"; MessagesFile: "compiler:Default.isl"
;Name: "de"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: 

[Files]
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\Resurces\VKDriveSettings.exe"; DestDir: "{app}\Resurces"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\Resurces\DokanInstall_0.8.0-RC2.exe"; DestDir: "{app}\Resurces"; Flags: ignoreversion; AfterInstall: RunDokanInstaller;
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\VKDrive.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\DokanNet.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\EntityFramework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\EntityFramework.SqlServer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\log4net.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\System.Data.SQLite.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\VKDrive.application"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\VKDrive.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\VKDrive.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\x86\SQLite.Interop.dll"; DestDir: "{app}\x86"; Flags: ignoreversion
Source: "C:\Users\DnAp\Documents\Visual Studio 2015\Projects\VKDrive\VKDrive\bin\Release\x64\SQLite.Interop.dll"; DestDir: "{app}\x64"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


[Code]
// shared code for installing the products
#include "scripts\products.iss"
// helper functions
#include "scripts\products\stringversion.iss"
#include "scripts\products\winversion.iss"
#include "scripts\products\fileversion.iss"
#include "scripts\products\dotnetfxversion.iss"
#include "scripts\products\msiproduct.iss"
#include "scripts\products\dotnetfx45.iss"
#include "scripts\products\vcredist2013.iss"

function InitializeSetup(): boolean;
begin
	// initialize windows version
	initwinversion();
  dotnetfx45();
	vcredist2013();

	Result := true;
end;

procedure RunDokanInstaller;
var
  ResultCode: Integer;
begin
  if not Exec(ExpandConstant('{app}\Resurces\DokanInstall_0.8.0-RC2.exe /S'), '', '', SW_SHOWNORMAL,
    ewWaitUntilTerminated, ResultCode)
  then
    MsgBox('Dokan installer failed to run!' + #13#10 +
      SysErrorMessage(ResultCode), mbError, MB_OK);
end;






